export type UnableReason =
  | "CONFIG_MISSING"
  | "CONFIG_INVALID"
  | "POLICY_MISSING"
  | "PR_METADATA_INVALID"
  | "PR_TOO_LARGE"
  | "LINEAR_AUTH_FAILED"
  | "LINEAR_NOT_FOUND"
  | "LINEAR_UNAVAILABLE"
  | "LINEAR_CONTEXT_TOO_LARGE"
  | "CI_CONTEXT_UNAVAILABLE"
  | "SNAPSHOT_FAILED"
  | "STATE_LOAD_FAILED"
  | "REJUDGE_PANEL_FAILED"
  | "REJUDGE_JUDGE_FAILED"
  | "JUDGE_RESULT_INVALID"
  | "JUDGE_REPAIR_FAILED"
  | "CLOSURE_FAILED"
  | "CLOSURE_RESULT_INVALID"
  | "INTERNAL_ERROR";

export const UNABLE_REASONS = [
  "CONFIG_MISSING",
  "CONFIG_INVALID",
  "POLICY_MISSING",
  "PR_METADATA_INVALID",
  "PR_TOO_LARGE",
  "LINEAR_AUTH_FAILED",
  "LINEAR_NOT_FOUND",
  "LINEAR_UNAVAILABLE",
  "LINEAR_CONTEXT_TOO_LARGE",
  "CI_CONTEXT_UNAVAILABLE",
  "SNAPSHOT_FAILED",
  "STATE_LOAD_FAILED",
  "REJUDGE_PANEL_FAILED",
  "REJUDGE_JUDGE_FAILED",
  "JUDGE_RESULT_INVALID",
  "JUDGE_REPAIR_FAILED",
  "CLOSURE_FAILED",
  "CLOSURE_RESULT_INVALID",
  "INTERNAL_ERROR",
] as const satisfies readonly UnableReason[];
